name: Update README with itch.io game data

on:
  workflow_dispatch:  # Permite ejecutar manualmente el workflow desde GitHub
  schedule:
    - cron: '0 0 * * *'  # Ejecuta el workflow todos los días a la medianoche (opcional)

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests

    - name: Update README.md
      env:
        ITCH_IO_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}  # Refiere al secreto aquí
      run: |
        python <<EOF
        import requests

        API_KEY = '${{ secrets.ITCH_IO_API_KEY }}'
        GAME_ID = '2256465'

        url = f'https://itch.io/api/1/{API_KEY}/game/{GAME_ID}'
        response = requests.get(url)

        if response.status_code == 200:
            data = response.json().get('game', {})
            title = data.get('title', 'Título no disponible')
            game_url = data.get('url', 'URL no disponible')
            created_at = data.get('created_at', 'Fecha no disponible')
            published_at = data.get('published_at', 'Fecha no disponible')
            platforms = []
            if data.get('p_windows', False):
                platforms.append('Windows')
            platforms_str = ', '.join(platforms) if platforms else 'No disponible'
            short_text = data.get('short_text', 'Descripción no disponible')

            readme_content = f"""
          # {title} - Terror & Puzzle Game

          ![Cover Image]({data.get('cover_url', '')})

          ## Descripción
          {short_text}

          **Supported Platforms**: {platforms_str}

          **Creation Date**: {created_at}

          **Publish Date**: {published_at}

          ## Features

          * Inventary by ScriptableObjects with photo, description and other stats.
          * Realistic movement.
          * Object Examinator.
          * Lighting with baking.
          * Minigames based purely on UI.

          
          ## <a href="https://youtu.be/vVJ0DhUESY4?si=snsCS6nh3vyk_vWx"> Trailer Video on YouTube </a>
          
          <img src="https://github.com/lucasgarciadominguez/Assets/blob/main/Captura4.png" width="800">
          
          <img src="https://github.com/lucasgarciadominguez/Assets/blob/main/Captura5.png" width="800">
          
          ## Stats

          <table>
                <thead>
                  <tr>
                    <th></th>
                    <th>Itch.io</th>
                  </tr>
                </thead>
                <tbody>
                      <tr>
                        <td>Views</td>
                        <td>+800</td>
                      </tr>
                      <tr>
                        <td>Downloads</td>
                        <td>+250</td>
                      </tr>
                </tbody>
            </table>

          ## Contact
          <table>
            <thead>
              <tr>
                <th>Full Name</th>
                <th>GitHub</th>
                <th>LinkedIn</th>
              </tr>
            </thead>
            <tbody>
                  <tr>
                    <td>Lucas Garcia</td>
                    <td><a href="https://github.com/lucasgarciadominguez">lucasgarciadominguez</a></td>
                    <td><a href="https://www.linkedin.com/in/lucas-garcia-dominguez/">Lucas Garcia Dominguez</a></td>
                  </tr>
                  <tr>
                    <td>Miguel Rodriguez</td>
                    <td><a href="https://github.com/waterproofcandlestudio">waterproofcandlestudio</a></td>
                    <td><a href="https://www.linkedin.com/in/miguel-rodriguez-gallego/">Miguel Rodriguez Gallego<a/></td>
                  </tr>
                  <tr>
                    <td>Samuel Robinson</td>
                    <td></td>
                    <td><a href="https://www.linkedin.com/in/samuel-robinson-210232268/">Samuel Robinson<a/></td>
                  </tr>
            </tbody>
          </table>
          </html>

          [Play now]({game_url})

            """

            with open("README.md", "w") as readme_file:
                readme_file.write(readme_content)
        else:
            print(f"Error al obtener datos del juego: {response.status_code}")
        EOF

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Updated README with latest game data"
        git push https://x-access-token:${{ secrets.MY_PAT_TOKEN }}@github.com/lucasgarciadominguez/Horror-Project.git HEAD:main 

